const mongoose = require("mongoose");

const BackupSchema = new mongoose.Schema({
  filename: {
    type: String,
    required: true,
    unique: true,
    trim: true
  },
  path: {
    type: String,
    required: true,
    trim: true
  },
  size: {
    type: Number,
    required: true,
    min: 0
  },
  type: {
    type: String,
    enum: ["full", "patients", "appointments", "automatic"],
    required: true,
    default: "full"
  },
  status: {
    type: String,
    enum: ["pending", "success", "failed", "restored"],
    default: "pending"
  },
  metadata: {
    patients: { type: Number, default: 0 },
    appointments: { type: Number, default: 0 },
    version: { type: String, default: "1.0.0" },
    scheduled: { type: Boolean, default: false },
    autoGenerated: { type: Boolean, default: false }
  },
  expiresAt: {
    type: Date
  },
  restoredAt: {
    type: Date
  },
  createdAt: {
    type: Date,
    default: Date.now,
    index: -1
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
});

BackupSchema.index({ type: 1, status: 1 });
BackupSchema.index({ createdAt: -1 });
BackupSchema.index({ expiresAt: 1 });

BackupSchema.pre("save", function(next) {
  this.updatedAt = Date.now();
  next();
});

module.exports = mongoose.model("Backup", BackupSchema);